import Constants from "expo-constants";
import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";

("use strict");
const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

var React = require("react-native");
const styles = StyleSheet.create({
  mainContainer: {
    minWidth: Dimensions.get("window").width,
  },
  card: {
    alignSelf: "center",
    alignItems: "center",
    width: "90%",
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.45)",
    borderRadius: 10,
    marginBottom: 20,
  },
  cardTitle: {
    marginTop: 40,
    marginLeft: 20,
    fontSize: 26,
    fontWeight: "700",
    color: "white",
    textShadowColor: "rgba(0, 0, 0, 0.45)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 5,
  },
  cardIMG: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    resizeMode: "cover",
  },
  cardGroup: {
    marginLeft: 20,
    alignSelf: "flex-start",
    fontSize: 16,
    fontWeight: "600",
    color: "white",
    textShadowColor: "rgba(0, 0, 0, 0.45)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 5,
  },
  cardTime: {
    fontSize: 14,
    alignSelf: "flex-start",
    fontWeight: "700",
    color: "white",
    width: "100%",
    justifyContent: "flex-start",
    textShadowColor: "rgba(0, 0, 0, 0.45)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 5,
  },
  cardLocation: {
    fontSize: 14,
    color: "white",
    width: "100%",
    justifyContent: "flex-start",
    textShadowColor: "rgba(0, 0, 0, 0.45)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 5,
  },
  cardEnd: {
    marginLeft: 20,
    fontSize: 16,
    fontWeight: "600",
    color: "white",
    backgroundColor: "red",
    borderRadius: 10,
    width: "200",
    maxWidth: "100%",
    textShadowColor: "rgba(0, 0, 0, 0.45)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 5,
  },
  shadowProp: {
    shadowColor: "#171717",
    shadowOffset: { width: -2, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  topContainer: {
    flexDirection: "row",
    width: Dimensions.get("window").width,
    height: 50,
    alignContent: "center",
    alignItems: "baseline",
  },
  centerContainer: {
    justifyContent: "center",
    marginBottom: 20,
    padding: 20,
  },
  spaceEvenly: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: Dimensions.get("window").width,
    padding: 10,
  },
  flexContainer: {
    width: "100%",
    justifyContent: "center",
    flexDirection: "row",
    padding: 10,
    width: Dimensions.get("window").width,
  },
  value: {
    marginLeft: 30,
    marginRight: 30,
    alignSelf: "flex-end",
    justifyContent: "flex-end",
    fontSize: 12,
    fontStyle: "italic",
  },
  type: {
    marginLeft: 30,
    marginRight: 30,
    alignSelf: "flex-start",
    justifyContent: "flex-start",
    fontSize: 17,
    fontWeight: "700",
  },

  topRightContainer: {
    minWidth: "50%",
    alignItems: "center",
    alignSelf: "flex-start",
    flexDirection: "column",
    height: "100%",
  },
  topLeftContainer: {
    width: Dimensions.get("window").width / 2,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingRight: 25,
    flexDirection: "row",
  },
  addChatTxt: {
    width: 100,
    paddingBottom: 15,
  },
  onlineStatus: {
    marginLeft: 5,
    fontSize: 50,
    height: 50,
    width: 50,
    borderRadius: 10,
  },
  onlineStatusText: {
    fontSize: 10,
    marginTop: -60,
    fontWeight: "700",
    textAlign: "center",
    color: "#5050a5",
  },

  flexColorContainer: {
    flexDirection: "row",
    backgroundColor: "#5050a5",
    height: 40,
    alignItems: "center",
    alignContent: "center",
  },
  descriptionContainer: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
    padding: 20,
    backgroundColor: "#fefefe",
    fontSize: 14,
    fontStyle: "italic",
  },
  ikon: {
    height: 16,
    width: 16,
    fontSize: 16,
    marginLeft: 20,
    marginRight: 5,
    color: "white",
  },
  container: {
    padding: 20,
    backgroundColor: "#e5e5e5",
    borderRadius: 10,
    alignSelf: "center",
  },
  logo: {
    width: 140,
    height: 200,
    alignSelf: "center",
    marginTop: 20,
    marginBottom: 10,
  },
  scrollView: {
    backgroundColor: "pink",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
  },
  buttonContainer: {
    backgroundColor: "#5050a5",
    justifyContent: "center",
    padding: 16,
    margin: 10,
    marginLeft: 30,
    marginRight: 30,
    borderRadius: 10,
    height: 60,
  },
  valid: {
    backgroundColor: "#5050a5",
    justifyContent: "center",
    borderRadius: 10,
    padding: 20,
    margin: 10,
    height: 60,
    width: Dimensions.get("window").width / 2.3,
  },
  invalid: {
    backgroundColor: "#5050a5",
    justifyContent: "center",
    borderRadius: 10,
    padding: 20,
    margin: 10,
    height: 60,
    width: Dimensions.get("window").width / 2.3,
  },
  doubleButtonContainer: {
    backgroundColor: "#5050a5",
    borderRadius: 10,
    padding: 20,
    margin: 10,
    height: 60,
    width: Dimensions.get("window").width / 2.3,
  },
  divider: {
    height: 20,
    borderBottomWidth: 2,
    marginBottom: 5,
    borderColor: "#5050a5",
  },
  copy: {
    flexDirection: "row",
    alignSelf: "center",
  },
  copyContainer: {
    padding: 20,
    backgroundColor: "white",
    margin: 40,
    borderRadius: 10,
  },
  copyText: {
    color: "#5050a5",
    fontSize: 16,
  },
  copyLink: {
    color: "#5050a5",
    fontSize: 16,
    fontWeight: "700",
    marginLeft: -4,
  },
  headerIkon: {
    height: 40,
    width: 40,
    fontSize: 40,
    marginTop: -10,
    marginLeft: 10,
    marginRight: -10,
    color: "white",
  },
  blockHeaderText: {
    fontSize: 26,
    marginLeft: 20,
    color: "white",
  },
  subHeader: {
    marginTop: 15,
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 10,
    color: "#32305d",
  },
  header: {
    marginTop: 15,
    fontSize: 26,
    fontWeight: "700",
    marginBottom: 10,
    color: "#32305d",
    paddingLeft: 20,
    paddingRight: 20,
  },
  blockHeader: {
    fontWeight: "700",
    height: 80,
    paddingTop: 20,
    backgroundColor: "#32305d",
    padding: 20,
    paddingLeft: 0,
    flexDirection: "row",
  },
  input: {
    alignSelf: "center",
    borderColor: "#32305d",
    borderWidth: 1,
    width: "90%",
    marginLeft: 40,
    marginRight: 40,
    margin: 0,
    height: 60,
    fontSize: 20,
    borderRadius: 4,
    padding: 10,
  },
  label: {
    fontSize: 20,
    color: "#32305d",
    fontWeight: "700",
    marginLeft: 10,
  },
  errormsg: {
    fontSize: 15,
    color: "red",
    textAlign: "center",
    fontWeight: "400",
    marginLeft: 10,
  },
  shadow: {
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.9,
    shadowRadius: 4.65,
    elevation: 8,
  },
  chatroomText: {
    width: "80%",
    fontSize: 16,
    fontWeight: "700",
    color: "white",
  },
  chatroomButton: {
    width: "20%",
  },
  chatDeleteIcon: {
    color: "white",
    fontSize: 26,
    alignSelf: "flex-end",
  },
  chatroomItem: {
    flexDirection: "row",
    padding: 15,
    backgroundColor: "#5050a5",
    borderWidth: 2,
    borderRadius: 10,
    borderColor: "black",
    marginTop: 5,
  },
  chatroomList: {
    width: Dimensions.get("window").width,
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 40,
  },
  AddEvent: {
    width: Dimensions.get("window").width,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingRight: 25,
    flexDirection: "row",
    marginTop: 10,
    marginBottom: -20,
  },
  addEventText: {
    marginBottom: 15,
  },
  eventList: {
    marginTop: 30,
    marginBottom: 155,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: "#f5f5f5",
  },
  modalContainer: {
    padding: 10,
    alignSelf: "center",
  },
  modalContent: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
    alignSelf: "center",
    backgroundColor: "#f5f5f5",
  },
  modalInnerContent: {
    padding: 10,
  },
  modalToggle: {
    fontSize: 30,
    borderColor: "#f2f2f2",
    height: 50,
    borderRadius: 10,
    alignSelf: "flex-end",
  },
  modalClose: {
    fontSize: 30,
    alignSelf: "flex-end",
  },
  modalTweak: {
    marginTop: -60,
    marginBottom: 40,
  },
  formikContainer: {
    padding: 10,
    flex: 1,
  },
  formContainers: {
    padding: 10,
    flex: 1,
  },
  formInput: {
    backgroundColor: "white",
    borderWidth: 2,
    borderColor: "white",
  },

  StatusBar: {
    height: Constants.statusBarHeight,
    backgroundColor: "#32305d",
  },

  //EditProfile

  avatarContainer: {
    padding: 20,
  },
  userDetails: {
    width: "65%",
    padding: 20,
  },
  userDetailsStore: {
    width: "100%",
    padding: 20,
  },
  avatarEdit: {
    width: 150,
    height: 150,
    borderRadius: 75,
    margin: 10,
    alignSelf: "center",
  },
  avatarDef: {
    width: 125,
    height: 125,
    borderRadius: 62,
    alignSelf: "center",
  },
});

export default styles;
