export class Chatroom {
    // title: string;
    // chatmessages: Chatmessage[];
    // imageUrl: string;
    // id?: string;

    constructor(public title: string, public chatmessages: Chatmessage[], public imageUrl: string, public id?: string) {
        // this.id = id;
        // this.title = title;
        // this.chatmessages = chatmessages;
        // this.imageUrl = imageUrl;
    }
}

export class Chatmessage {
    constructor(public text: string, public timestamp: Date) { }
}


eyJhbGciOiJSUzI1NiIsImtpZCI6ImJlYmYxMDBlYWRkYTMzMmVjOGZlYTU3ZjliNWJjM2E2YWIyOWY1NTUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVhY3QtZmlyc3QtNDFiYjUiLCJhdWQiOiJyZWFjdC1maXJzdC00MWJiNSIsImF1dGhfdGltZSI6MTY1MjEzMzEwOCwidXNlcl9pZCI6IjZSOVdFUGFrWUdnaUtPTTNLOUtMZXVTUDBqODIiLCJzdWIiOiI2UjlXRVBha1lHZ2lLT00zSzlLTGV1U1AwajgyIiwiaWF0IjoxNjUyMTMzMTA4LCJleHAiOjE2NTIxMzY3MDgsImVtYWlsIjoiYW5kQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhbmRAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.n1z7noFAv8t7U7vNK7TJ9uU07i1SQIfqg1M1625fwPduXDXjbPGGGvvvl7DBGnSCoNq1YqgwW-JgsV2FMKIvLPNxJ_ro_xb79hnu2LsJOwvwH6ZLpNM02PpdiVz7CLJpohOCev4qjnki18nPI3_Zsq55O0sLlaMkEPz-kbsxOPc8ilW5A_tuCIK7k6N0BVje1t--3gwsuxqQ1d2zMe0effb0Id-6bv05apTmGiWvVYHfg1LKoeSdu_LYaAfd0ylw9_1KkHyvjzbug-DpEtRocjTC-Eb6dceoykdjkHrtun5rVBMFdcX3LvTau4QBC5A7b_1lpBUWFtKvzmExz2JZ9g
eyJhbGciOiJSUzI1NiIsImtpZCI6ImJlYmYxMDBlYWRkYTMzMmVjOGZlYTU3ZjliNWJjM2E2YWIyOWY1NTUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVhY3QtZmlyc3QtNDFiYjUiLCJhdWQiOiJyZWFjdC1maXJzdC00MWJiNSIsImF1dGhfdGltZSI6MTY1MjE0MTYyNywidXNlcl9pZCI6IjZSOVdFUGFrWUdnaUtPTTNLOUtMZXVTUDBqODIiLCJzdWIiOiI2UjlXRVBha1lHZ2lLT00zSzlLTGV1U1AwajgyIiwiaWF0IjoxNjUyMTQxNjI3LCJleHAiOjE2NTIxNDUyMjcsImVtYWlsIjoiYW5kQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhbmRAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.JvYZVc3eyaQOw3vmHv2VioLacNSFsz6ihJhd31tLmBS7kRuJBZbBPZW1FqaoJgiRl0XzptpQj8AdB4-DFQNxkeB-a0cLUW6WqI9nkgG5WeNpPv3NV12IuoihZWArz6JLzR4qXkp1w4-Cx6ZjYdj1b1Qz7Dsd4jvUgGGjsnXUeXMIu9Qk45Mq97qHgPvKPJbn8MV8T2qRpPO2UkymluHtkWYFMy2R0V3IRBKlmopM9haGq0blGc15VUS9gPBVss1kl0sCi8gD0_AjGIpvaPS-LWgXDBR1t6LISPkyMxxJrvYz_FGtgk46t7pEYzMjAFNiygnrCjLdhfLTkrHdjTF2sQ